server:
  port: 8222
spring:
  application:
    name: swcamp-user-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: root
    password: 1221
