#????? ?? ??? ????
server:
  port: 8081
  tomcat:
    max-connections: 200
    #?? ?? ?? ?
    #??? ?? ???? ???? ??? default 8192

#?? ??? ?? ??
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB     #??? ? ? ?? ? ?? ??
      max-request-size: 200MB  #??? ??? ? ??
  web:
    resources:
      static-locations: file:///Users/dong/Desktop/02_java/fileUpload/ #?? ??? ??
      cache-period: 3600                                              #? ????? ?? ??(? ??, 1??)

filepath: /Users/dong/Desktop/02_java/fileUpload